version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Run my script
          command: |
            echo "This is my simple script!"
            # Тут можна додати додаткові команди, наприклад:
            ./main.sh

  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: This is unit tests
          command: |
            echo "This is my unit tests"

workflows:
  app_build_and_test:
    jobs:
      - build
      - test:
          filters:
            branches:
              only: master
          requires:
            - build