version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Run my script
          command: |
            echo "This is my simple script!"
            # Тут можна додати додаткові команди, наприклад:
            ./main.sh

  build1:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Run my script
          command: |
            echo "This is my simple build 1!"

workflows:
  app_build_and_test:
    jobs:
      - build
      - build1:
          filters:
            branches:
              only: master
          requires:
            - build